stock_transactions_create:
  path: /portfolio/transactions
  methods: POST
  defaults: { _controller: 'App\Controller\StockTransactionController::createAction' }
  
stock_transactions_update:
  path: /portfolio/transactions
  methods: PUT
  defaults: { _controller: 'App\Controller\StockTransactionController::putAction' }
  
stock_transactions_list:
  path: /portfolio/transactions
  methods: GET
  defaults: { _controller: 'App\Controller\StockTransactionController::listAction' }
  
stock_transactions_get:
  path: /portfolio/transactions/{id}
  methods: GET
  defaults: { _controller: 'App\Controller\StockTransactionController::getAction' }
  
stock_transactions_delete:
  path: /portfolio/transactions/{id}
  methods: DELETE
  defaults: { _controller: 'App\Controller\StockTransactionController::deleteAction' }
  
portfolio_get:
  path: /portfolio
  methods: GET
  defaults: { _controller: 'App\Controller\StockTransactionController::getPortfolioAction' }